[package]
name = "bpfcontain-rs"
version = "0.1.0"
authors = ["William Findlay <william@williamfindlay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.36"
libbpf-rs = "0.6.0"
clap = "2.33.3"
libc = "0.2.81"
daemonize = "0.4.1"
log = "0.4.11"
simple_logger = "1.11.0"

[dev-dependencies]
libbpf-cargo = "0.4.0"
