daemon:
  # Path to logfile
  logFile: /var/log/bpfcontain.log
  # Path to pidfile
  pidFile: /run/bpfcontain.pid
  # Working directory
  workDir: /var/lib/bpfcontain
  # IP address to use for websocket server
  websocketIP: "0.0.0.0:3030"
  # Log level
  verbosity: INFO

policy:
  # Path to policy directory
  dir: /var/lib/bpfcontain/policy

bpf:
  # Possible values: [allow, deny, taint, info, warn]
  auditLevel: [deny, taint, info, warn]
